---
- name: Install Go (macOS)
  community.general.homebrew:
    name: go
    state: present
  when: ansible_facts['system'] == 'Darwin'

- name: Install Go (Arch Linux)
  community.general.pacman:
    name: go
    state: present
  become: true
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Install Go (Ubuntu)
  apt:
    name: golang-go
    state: present
  become: true
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Install fnm (macOS)
  community.general.homebrew:
    name: fnm
    state: present
  when: ansible_facts['system'] == 'Darwin'

- name: Install fnm (Arch Linux)
  community.general.pacman:
    name: fnm
    state: present
  become: true
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Install fnm (Ubuntu)
  ansible.builtin.shell: curl -fsSL https://fnm.vercel.app/install | bash
  args:
    creates: "{{ home }}/.local/share/fnm/fnm"
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Check if fnm has installed any Node version
  command: fnm list
  register: fnm_list
  changed_when: false
  failed_when: false

- name: Install latest Node via fnm
  command: fnm install --latest
  when: fnm_list.stdout is not search('v\\d+\\.\\d+\\.\\d+')

- name: Add fnm env to zshrc
  lineinfile:
    path: "{{ home }}/.zshrc"
    line: 'eval "$(fnm env --use-on-cd --shell zsh)"'
    create: true
