watch_stylesheet: true
watch_config: true

bars:
  yasb-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark: false
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: ["komorebi_workspaces", "komorebi_active_layout", "active_window"]
      center: ["clock"]
      right: ["weather", "cpu", "memory", "wifi", "battery"]

widgets:
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      max_length: 48
      max_length_ellipsis: "..."
      monitor_exclusive: false

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      time_remaining_natural: true

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%H:%M:%S %Z}"
      label_alt: "{%d-%m-%y %H:%M:%S %Z}"
      timezones: ["America/New_York"]
      callbacks:
        on_middle: "exec explorer.exe shell:Appsfolder\\Microsoft.WindowsAlarms_8wekyb3d8bbwe!App"
        on_right: "next_timezone"

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "\uf4bc {info[histograms][cpu_percent]}"
      label_alt: "\uf4bc CPU: {info[percent][total]}%"
      update_interval: 500
      histogram_icons:
        - '\u3000' # 0%
        - '\u3001' # 10%
        - '\u3002' # 20%
        - '\u3003' # 30%
        - '\u3004' # 40%
        - '\u3005' # 50%
        - '\u3006' # 60%
        - '\u3007' # 70%
        - '\u3008' # 80%+
      histogram_num_columns: 10

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "\ue266 {virtual_mem_free}"
      label_alt: "\ue266 {virtual_mem_percent}%"
      update_interval: 5000
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "Komorebi Offline"
      label_workspace_btn: "{index}"
      label_default_name: "{index}"
      label_zero_index: false
      hide_empty_workspaces: false

  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: false
      label: "{icon}"
      layout_icons:
        bsp: "[\\\\]"
        columns: "[||]"
        rows: "[==]"
        vertical_stack: "[V]="
        horizontal_stack: "[H]="
        ultrawide_vertical_stack: "||="
        monocle: "[M]"
        maximised: "[X]"
        floating: "><>"
        paused: "[P]"
      callbacks:
        on_left: "next_layout"
        on_middle: "toggle_monocle"
        on_right: "prev_layout"

  # Some custom widgets

  explorer_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf07c"
      label_alt: "Explorer"
      class_name: "explorer-widget"
      exec_options:
        run_once: true
      callbacks:
        on_left: "exec explorer.exe"
        on_right: "toggle_label"

  ip_info:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf3c5 {data[city]}, {data[region]}"
      label_alt: "\uf3c5 {data[ip]} [{data[country]}]"
      class_name: "ip-info-widget"
      exec_options:
        run_cmd: "curl.exe https://ipinfo.io"
        run_interval: 120000 # every 5 minutes
        return_format: "json"
      callbacks:
        on_left: "toggle_label"
        on_middle: "exec cmd /c ncpa.cpl" # open network settings
        on_right: "exec cmd /c start https://ipinfo.io/{data[ip]} " # open ipinfo in browser

  weather:
    type: "yasb.custom.CustomWidget"
    options:
      class_name: "weather-widget"
      label: "\uf0c2 {data[current_condition][0][temp_F]}\u00b0f"
      label_alt: "\uf0c2 {data[current_condition][0][weatherDesc][0][value]}"
      exec_options:
        run_cmd: "curl.exe wttr.in/Orlando?format=j1"
        # run every hour
        run_interval: 3600000
        return_format: "json"

  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "{wifi_icon}"
      label_alt: "{wifi_icon} {wifi_name}"
      update_interval: 5000
      wifi_icons:
        - "\udb82\udd2e" # 0% strength (no wifi)
        - "\udb82\udd1f" # 1-25% strength
        - "\udb82\udd22" # 26-50% strength
        - "\udb82\udd25" # 51-75% strength
        - "\udb82\udd28" # 76-100% strength. Alternate theming: \uf1eb
      callbacks:
        on_middle: "do_nothing"
        on_right: "exec cmd.exe /c start ms-settings:network"
