---
- name: Create ~/.local/bin
  file:
    path: "{{ home }}/.local/bin"
    state: directory

- name: Find executable local scripts
  find:
    paths:
      - "{{ dotfiles_dir }}/bin/local/bin"
      - "{{ dotfiles_dir }}/bin/local/scripts"
    file_type: file
  register: local_scripts

- name: Symlink local scripts to ~/.local/bin
  file:
    src: "{{ item }}"
    dest: "{{ home }}/.local/bin/{{ item | basename }}"
    state: link
    force: true
  loop: "{{ local_scripts.files | map(attribute='path') | list }}"

- name: Add ~/.local/bin to PATH in zshrc
  lineinfile:
    path: "{{ home }}/.zshrc"
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    create: true
