---
- name: Tap oh-my-posh
  community.general.homebrew_tap:
    name: jandedobbeleer/oh-my-posh

- name: Install oh-my-posh
  community.general.homebrew:
    name: oh-my-posh
    state: present

- name: Symlink oh-my-posh theme
  file:
    src: "{{ dotfiles_dir }}/myposh.omp.json"
    dest: "{{ home }}/myposh.omp.json"
    state: link
    force: true

- name: Add oh-my-posh init to zshrc
  lineinfile:
    path: "{{ home }}/.zshrc"
    line: 'eval "$(oh-my-posh --init --shell zsh --config ~/myposh.omp.json)"'
    create: true
