---
- name: Tap oh-my-posh (macOS)
  community.general.homebrew_tap:
    name: jandedobbeleer/oh-my-posh
  when: ansible_facts['system'] == 'Darwin'

- name: Install oh-my-posh (macOS)
  community.general.homebrew:
    name: oh-my-posh
    state: present
  when: ansible_facts['system'] == 'Darwin'

- name: Install oh-my-posh (Linux)
  ansible.builtin.shell: curl -s https://ohmyposh.dev/install.sh | bash
  args:
    creates: "{{ home }}/.local/bin/oh-my-posh"
  when: ansible_facts['system'] == 'Linux'

- name: Symlink oh-my-posh config directory
  file:
    src: "{{ dotfiles_dir }}/ohmyposh"
    dest: "{{ home }}/.config/ohmyposh"
    state: link
    force: true

- name: Add oh-my-posh init to zshrc
  lineinfile:
    path: "{{ home }}/.zshrc"
    line: 'eval "$(oh-my-posh init zsh --config ~/.config/ohmyposh/zen.toml)"'
    create: true
