---
- name: Tap oh-my-posh
  community.general.homebrew_tap:
    name: jandedobbeleer/oh-my-posh

- name: Install oh-my-posh
  community.general.homebrew:
    name: oh-my-posh
    state: present

- name: Symlink oh-my-posh config directory
  file:
    src: "{{ dotfiles_dir }}/ohmyposh"
    dest: "{{ home }}/.config/ohmyposh"
    state: link
    force: true

- name: Add oh-my-posh init to zshrc
  lineinfile:
    path: "{{ home }}/.zshrc"
    line: 'eval "$(oh-my-posh init zsh --config ~/.config/ohmyposh/zen.toml)"'
    create: true
